
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myTour_development

test:
  <<: *default
  database: myTour_test

production:
  <<: *default
  database: myTour_production
  username: myTour
  password: <%= ENV['MYTOUR_DATABASE_PASSWORD'] %>
